import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import api from '../services/api';
import { toast } from 'react-toastify';
import './VerificationCodes.css';

const VerificationCodes = () => {
  const [codes, setCodes] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchCodes();
  }, []);

  const fetchCodes = async () => {
    try {
      const { data } = await api.get('/patients/verification-codes');
      setCodes(data.data);
    } catch (error) {
      toast.error('Failed to load verification codes');
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
    toast.success('Copied to clipboard!');
  };

  const getTimeRemaining = (expiresAt) => {
    const now = new Date();
    const expiry = new Date(expiresAt);
    const diff = expiry - now;
    
    if (diff <= 0) return 'Expired';
    
    const hours = Math.floor(diff / (1000 * 60 * 60));
    const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
    
    if (hours > 0) {
      return `${hours}h ${minutes}m remaining`;
    }
    return `${minutes}m remaining`;
  };

  const isExpiringSoon = (expiresAt) => {
    const now = new Date();
    const expiry = new Date(expiresAt);
    const diff = expiry - now;
    return diff <= 6 * 60 * 60 * 1000; // 6 hours
  };

  if (loading) return <div className="loading">Loading...</div>;

  return (
    <div>
      <div className="page-header">
        <h1>Parent Verification Codes</h1>
        <Link to="/patients" className="btn btn-secondary">Back to Patients</Link>
      </div>

      <div className="card" style={{ marginBottom: '2rem' }}>
        <div className="verification-header">
          <div className="verification-header-info">
            <h3>Active Verification Codes</h3>
            <p>
              Codes generated for parents to link their children's accounts
            </p>
          </div>
          <button onClick={fetchCodes} className="btn btn-secondary">
            Refresh
          </button>
        </div>
      </div>

      {codes.length > 0 ? (
        <div className="card">
          <table className="data-table">
            <thead>
              <tr>
                <th>Patient</th>
                <th>Parent Details</th>
                <th>Verification Code</th>
                <th>Generated By</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {codes.map((code) => (
                <tr key={code._id} className={isExpiringSoon(code.expiresAt) ? 'verification-row-expiring' : ''} data-label="">
                  <td data-label="Patient">
                    <div className="verification-patient-info">
                      <span className="verification-patient-name">{code.patientId?.name}</span>
                      <small className="verification-detail">
                        DOB: {new Date(code.patientId?.dateOfBirth).toLocaleDateString()}
                      </small>
                      <small className="verification-detail">
                        ID: {code.patientId?._id}
                      </small>
                    </div>
                  </td>
                  <td data-label="Parent">
                    <div className="verification-patient-info">
                      <span className="verification-patient-name">{code.parentName}</span>
                      <small className="verification-detail">
                        {code.parentEmail}
                      </small>
                    </div>
                  </td>
                  <td data-label="Code">
                    <div className="verification-code-cell">
                      <code className="verification-code-display">
                        {code.code}
                      </code>
                      <button 
                        onClick={() => copyToClipboard(code.code)} 
                        className="btn btn-secondary verification-copy-btn"
                      >
                        Copy
                      </button>
                    </div>
                  </td>
                  <td data-label="Generated By">
                    <div className="verification-patient-info">
                      <span className="verification-patient-name">{code.generatedBy?.name}</span>
                      <small className="verification-detail">
                        {new Date(code.createdAt).toLocaleString()}
                      </small>
                    </div>
                  </td>
                  <td data-label="Status">
                    <div>
                      <span className={`verification-status ${isExpiringSoon(code.expiresAt) ? 'expiring' : 'active'}`}>
                        {getTimeRemaining(code.expiresAt)}
                      </span>
                      <br />
                      <small className="verification-detail">
                        Expires: {new Date(code.expiresAt).toLocaleString()}
                      </small>
                    </div>
                  </td>
                  <td data-label="Actions">
                    <div className="verification-actions">
                      <button 
                        onClick={() => copyToClipboard(`Patient ID: ${code.patientId?._id}\nVerification Code: ${code.code}`)} 
                        className="btn btn-primary"
                      >
                        Copy Both
                      </button>
                      <Link 
                        to={`/patients/${code.patientId?._id}`} 
                        className="btn btn-secondary"
                      >
                        View Patient
                      </Link>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <div className="card verification-empty">
          <h3>No Active Verification Codes</h3>
          <p>
            No verification codes have been generated yet. Generate codes from individual patient profiles.
          </p>
          <Link to="/patients" className="btn btn-primary">View Patients</Link>
        </div>
      )}

      <div className="card verification-info-card">
        <h3>How Verification Codes Work</h3>
        <div className="verification-info-content">
          <ol>
            <li><strong>Generate Code:</strong> From a patient's profile, click "Generate Parent Code"</li>
            <li><strong>Provide to Parent:</strong> Give the Patient ID and Verification Code to the parent</li>
            <li><strong>Parent Registration:</strong> Parent creates account with the specified email</li>
            <li><strong>Link Child:</strong> Parent uses the codes to link their child's records</li>
            <li><strong>Access Granted:</strong> Parent can now view immunization records and receive notifications</li>
          </ol>
          
          <div className="verification-security-box">
            <strong>Security Features:</strong>
            <ul>
              <li>Codes expire after 48 hours</li>
              <li>Email verification ensures correct parent account</li>
              <li>One-time use codes prevent unauthorized access</li>
              <li>Only healthcare staff can generate codes</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default VerificationCodes;