import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import api from '../services/api';
import { toast } from 'react-toastify';

const VerificationCodes = () => {
  const [codes, setCodes] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchCodes();
  }, []);

  const fetchCodes = async () => {
    try {
      const { data } = await api.get('/patients/verification-codes');
      setCodes(data.data);
    } catch (error) {
      toast.error('Failed to load verification codes');
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
    toast.success('Copied to clipboard!');
  };

  const getTimeRemaining = (expiresAt) => {
    const now = new Date();
    const expiry = new Date(expiresAt);
    const diff = expiry - now;
    
    if (diff <= 0) return 'Expired';
    
    const hours = Math.floor(diff / (1000 * 60 * 60));
    const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
    
    if (hours > 0) {
      return `${hours}h ${minutes}m remaining`;
    }
    return `${minutes}m remaining`;
  };

  const isExpiringSoon = (expiresAt) => {
    const now = new Date();
    const expiry = new Date(expiresAt);
    const diff = expiry - now;
    return diff <= 6 * 60 * 60 * 1000; // 6 hours
  };

  if (loading) return <div className="loading">Loading...</div>;

  return (
    <div>
      <div className="page-header">
        <h1>Parent Verification Codes</h1>
        <Link to="/patients" className="btn btn-secondary">Back to Patients</Link>
      </div>

      <div className="card" style={{ marginBottom: '2rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
          <div>
            <h3>Active Verification Codes</h3>
            <p style={{ color: '#7f8c8d', margin: 0 }}>
              Codes generated for parents to link their children's accounts
            </p>
          </div>
          <button onClick={fetchCodes} className="btn btn-secondary">
            Refresh
          </button>
        </div>
      </div>

      {codes.length > 0 ? (
        <div className="card">
          <table className="data-table">
            <thead>
              <tr>
                <th>Patient</th>
                <th>Parent Details</th>
                <th>Verification Code</th>
                <th>Generated By</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {codes.map((code) => (
                <tr key={code._id} style={{
                  backgroundColor: isExpiringSoon(code.expiresAt) ? '#fff3cd' : 'transparent'
                }}>
                  <td>
                    <div>
                      <strong>{code.patientId?.name}</strong>
                      <br />
                      <small style={{ color: '#7f8c8d' }}>
                        DOB: {new Date(code.patientId?.dateOfBirth).toLocaleDateString()}
                      </small>
                      <br />
                      <small style={{ color: '#7f8c8d' }}>
                        ID: {code.patientId?._id}
                      </small>
                    </div>
                  </td>
                  <td>
                    <div>
                      <strong>{code.parentName}</strong>
                      <br />
                      <small style={{ color: '#7f8c8d' }}>
                        {code.parentEmail}
                      </small>
                    </div>
                  </td>
                  <td>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                      <code style={{ 
                        backgroundColor: '#f8f9fa', 
                        padding: '0.5rem', 
                        borderRadius: '4px',
                        fontSize: '1.1rem',
                        fontWeight: 'bold',
                        color: '#e74c3c'
                      }}>
                        {code.code}
                      </code>
                      <button 
                        onClick={() => copyToClipboard(code.code)} 
                        className="btn btn-secondary" 
                        style={{ padding: '0.25rem 0.5rem', fontSize: '0.8rem' }}
                      >
                        Copy
                      </button>
                    </div>
                  </td>
                  <td>
                    <div>
                      {code.generatedBy?.name}
                      <br />
                      <small style={{ color: '#7f8c8d' }}>
                        {new Date(code.createdAt).toLocaleString()}
                      </small>
                    </div>
                  </td>
                  <td>
                    <div>
                      <span style={{ 
                        color: isExpiringSoon(code.expiresAt) ? '#f39c12' : '#27ae60',
                        fontWeight: 'bold'
                      }}>
                        {getTimeRemaining(code.expiresAt)}
                      </span>
                      <br />
                      <small style={{ color: '#7f8c8d' }}>
                        Expires: {new Date(code.expiresAt).toLocaleString()}
                      </small>
                    </div>
                  </td>
                  <td>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                      <button 
                        onClick={() => copyToClipboard(`Patient ID: ${code.patientId?._id}\nVerification Code: ${code.code}`)} 
                        className="btn btn-primary" 
                        style={{ fontSize: '0.8rem', padding: '0.25rem 0.5rem' }}
                      >
                        Copy Both
                      </button>
                      <Link 
                        to={`/patients/${code.patientId?._id}`} 
                        className="btn btn-secondary" 
                        style={{ fontSize: '0.8rem', padding: '0.25rem 0.5rem', textAlign: 'center' }}
                      >
                        View Patient
                      </Link>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <div className="card" style={{ textAlign: 'center', padding: '3rem' }}>
          <h3>No Active Verification Codes</h3>
          <p style={{ color: '#7f8c8d', marginBottom: '2rem' }}>
            No verification codes have been generated yet. Generate codes from individual patient profiles.
          </p>
          <Link to="/patients" className="btn btn-primary">View Patients</Link>
        </div>
      )}

      <div className="card" style={{ marginTop: '2rem' }}>
        <h3>How Verification Codes Work</h3>
        <div style={{ color: '#7f8c8d' }}>
          <ol style={{ paddingLeft: '1.5rem' }}>
            <li><strong>Generate Code:</strong> From a patient's profile, click "Generate Parent Code"</li>
            <li><strong>Provide to Parent:</strong> Give the Patient ID and Verification Code to the parent</li>
            <li><strong>Parent Registration:</strong> Parent creates account with the specified email</li>
            <li><strong>Link Child:</strong> Parent uses the codes to link their child's records</li>
            <li><strong>Access Granted:</strong> Parent can now view immunization records and receive notifications</li>
          </ol>
          
          <div style={{ marginTop: '1.5rem', padding: '1rem', backgroundColor: '#e8f4fd', borderRadius: '4px' }}>
            <strong>Security Features:</strong>
            <ul style={{ paddingLeft: '1.5rem', margin: '0.5rem 0' }}>
              <li>Codes expire after 48 hours</li>
              <li>Email verification ensures correct parent account</li>
              <li>One-time use codes prevent unauthorized access</li>
              <li>Only healthcare staff can generate codes</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default VerificationCodes;